/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shanmuk' at '9/12/15 1:02 AM' with Gradle 2.9
 *
 * @author shanmuk, @date 9/12/15 1:02 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
